on:
  workflow_call:
    inputs:
      FILE:
        type: string
        default: ""
      CONTEXT:
        type: string
        default: ""
      BUILD_ARGS:
        type: string
        default: ""
      DOCKERHUB_REPO:
        description: 'Dockerhub repository'
        type: string
        default: "${{ github.repository }}"
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_PASS:
        required: true

jobs:
  dockerhub:
    name: "Publish to Dockehub"
    runs-on: ubuntu-20.04
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.DOCKERHUB_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - uses: actions/checkout@v2
        if: ${{ inputs.CONTEXT }}
        with:
          fetch-depth: 0

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        if: ${{ steps.meta.outputs.tags }}
        with:
          context: ${{ inputs.CONTEXT }}
          file: ${{ inputs.FILE }}
          build-args: ${{ inputs.BUILD_ARGS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
