on:
  workflow_call:
    inputs:
      DEPLOY_REPO:
        description: 'Gitops repository used for deployments'
        type: string
        default: aeternity/gitops-apps
      DEPLOY_APP:
        description: 'Application name in gitops repository, usually the caller repository name'
        type: string
        default: ${{ github.event.repository.name }}
      DEPLOY_ENV:
        description: 'Deployment environment name'
        type: string
        required: true
      DEPLOY_VERSION:
        description: 'Application version'
        type: string
        required: false
      DEPLOY_HOST_PREFIX:
        description: 'Deployment hostname prefix, usually $VERSION-'
        type: string
        required: false

jobs:
  rollback:
    name: "Rollback from Gitops"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.DEPLOY_REPO }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          ref: ${{ inputs.DEPLOY_ENV }}
          persist-credentials: false
          fetch-depth: 0

      - name: Configure git
        shell: bash
        run: |
          git config --local user.email "aeternity-bot@users.noreply.github.com"
          git config --local user.name "github-actions"

      - name: Update application version in Gitops repository
        if: ${{ inputs.DEPLOY_VERSION != '' }}
        shell: bash
        env:
          APP_ENV: ${{ inputs.DEPLOY_ENV }}
          APP_VERSION: ${{ inputs.DEPLOY_VERSION }}
          APP_HOST_PREFIX: ${{ inputs.DEPLOY_HOST_PREFIX }}
          APP_VERSION_SHA_LONG: ${{ github.sha }}
        run: |
          export APP_VERSION_SHA=${APP_VERSION_SHA_LONG:0:7}
          ./scripts/app.sh delete-version ${{ inputs.DEPLOY_APP }}
          ./scripts/app.sh delete-host ${{ inputs.DEPLOY_APP }}

      - name: Commit Gitops changes
        shell: bash
        env:
          APP_VERSION: ${{ inputs.DEPLOY_TAG || inputs.DEPLOY_VERSION }}
        run: |
          git add .
          git commit -m "Rollback ${{ inputs.DEPLOY_APP }} from ${{ inputs.DEPLOY_ENV }} - ${APP_VERSION}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ inputs.DEPLOY_REPO }}
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          branch: ${{ inputs.DEPLOY_ENV }}
