name: "Pull Request Cleanup"

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  rollback:
    uses: ./.github/workflows/_rollback-gitops.yml
    secrets: inherit
    with:
      DEPLOY_ENV: dev
      DEPLOY_APP: aepp-test
      DEPLOY_VERSION: "pr-${{ github.event.number }}"
      DEPLOY_SUBDOMAIN: "pr-${{ github.event.number }}-test"
  delete-tag:
    uses: ./.github/workflows/_delete-tag-docker.yml
    secrets: inherit
    with:
      DOCKERHUB_REPO: aeternitybot/aepp-test
      DOCKERHUB_TAG: "pr-${{ github.event.number }}"
